Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/jammy64"
    ubuntu.vm.network "private_network", type: "dhcp"
    ubuntu.vm.hostname = "ubuntu"
    ubuntu.vm.provision "shell", inline: <<-SHELL
      # Configurar la dirección IP estática en Ubuntu
      sudo ip addr add 172.16.1.61/24 dev enp0s8
      sudo ip link set dev enp0s8 up

      # Instalar rsyslog en Ubuntu
      sudo apt-get update
      sudo apt-get install -y rsyslog

      # Habilitar el envío de eventos a Rocky (172.16.1.62) mediante UDP

      echo '*.* @172.16.1.62:514' | sudo tee -a /etc/rsyslog.conf
      # Reiniciar rsyslog para aplicar los cambios
      sudo systemctl restart rsyslog
    SHELL
  end

  config.vm.define "rocky" do |rocky|
    rocky.vm.box = "generic/rocky9"
    rocky.vm.network "private_network", type: "dhcp"
    rocky.vm.hostname = "rocky"
    rocky.vm.provision "shell", inline: <<-SHELL
      # Configurar la dirección IP estática en Rocky
      sudo ip addr add 172.16.1.62/24 dev enp0s8
      sudo ip link set dev enp0s8 up

      # Instalar rsyslog en Rocky
      sudo yum install -y rsyslog

      # Abrir el puerto 514 (rsyslog) en firewalld
      sudo firewall-cmd --permanent --add-port=514/udp
      sudo firewall-cmd --reload

      # Configurar rsyslog para recibir eventos desde equipo Ubuntu (172.16.1.61) mediante UDP
      sudo sed -i 's/#module(load="imudp")/module(load="imudp")/' /etc/rsyslog.conf
      sudo sed -i 's/#input(type="imudp" port="514")/input(type="imudp" port="514")/' /etc/rsyslog.conf
      sudo sed -i 's/#module(load="imtcp")/module(load="imtcp")/' /etc/rsyslog.conf
      sudo sed -i 's/#input(type="imtcp" port="514")/input(type="imtcp" port="514")/' /etc/rsyslog.conf

      # Reiniciar rsyslog para aplicar los cambios
      sudo systemctl restart rsyslog
    SHELL
  end
end
